apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: giimall-acr-registry-vpc.cn-hangzhou.cr.aliyuncs.com/test/ai-agent-backend:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: ai-agent-backend-env
          volumeMounts:
            - name: data
              mountPath: /app/data
            - name: workspace
              mountPath: /app/workspace

          resources:
            requests:
              cpu: "1"
              memory: "4Gi"
            limits:
              cpu: "1"
              memory: "4Gi"

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: backend-data-pvc

        - name: workspace
          persistentVolumeClaim:
            claimName: backend-workspace-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: test
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
