"""稳定机器可读错误码（HTTP Problem Details ``code`` 字段真源）。"""

from __future__ import annotations

# 通用
INTERNAL_ERROR = "INTERNAL_ERROR"
VALIDATION_ERROR = "VALIDATION_ERROR"
NOT_FOUND = "NOT_FOUND"
PERMISSION_DENIED = "PERMISSION_DENIED"
AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"
TOKEN_ERROR = "TOKEN_ERROR"
CONFLICT = "CONFLICT"
RATE_LIMIT = "RATE_LIMIT"
EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
TOOL_EXECUTION_ERROR = "TOOL_EXECUTION_ERROR"
CHECKPOINT_ERROR = "CHECKPOINT_ERROR"

# Tenancy
TEAM_NOT_FOUND = "TEAM_NOT_FOUND"
TEAM_PERMISSION_DENIED = "TEAM_PERMISSION_DENIED"
PERSONAL_TEAM_NOT_INITIALIZED = "PERSONAL_TEAM_NOT_INITIALIZED"

# Gateway（管理面 / 鉴权 deps）
GATEWAY_ENTITLEMENT_EXHAUSTED = "GATEWAY_ENTITLEMENT_EXHAUSTED"
VIRTUAL_KEY_INVALID = "VIRTUAL_KEY_INVALID"
PLATFORM_API_KEY_INVALID = "PLATFORM_API_KEY_INVALID"
PLATFORM_API_KEY_MISSING_GATEWAY_PROXY_SCOPE = "PLATFORM_API_KEY_MISSING_GATEWAY_PROXY_SCOPE"
NO_PERSONAL_TEAM_FOR_PROXY = "NO_PERSONAL_TEAM_FOR_PROXY"
GATEWAY_TEAM_HEADER_INVALID = "GATEWAY_TEAM_HEADER_INVALID"
GATEWAY_TEAM_HEADER_REQUIRED = "GATEWAY_TEAM_HEADER_REQUIRED"
GATEWAY_VKEY_TEAM_HEADER_MISMATCH = "GATEWAY_VKEY_TEAM_HEADER_MISMATCH"
API_KEY_GATEWAY_GRANT_DENIED = "API_KEY_GATEWAY_GRANT_DENIED"
API_KEY_GATEWAY_GRANT_REQUIRED = "API_KEY_GATEWAY_GRANT_REQUIRED"
VIRTUAL_KEY_NOT_FOUND = "VIRTUAL_KEY_NOT_FOUND"
SYSTEM_VIRTUAL_KEY_FORBIDDEN = "SYSTEM_VIRTUAL_KEY_FORBIDDEN"
CREDENTIAL_API_KEY_DECRYPT_ERROR = "CREDENTIAL_API_KEY_DECRYPT_ERROR"
VIRTUAL_KEY_DECRYPT_ERROR = "VIRTUAL_KEY_DECRYPT_ERROR"
CREDENTIAL_NOT_FOUND = "CREDENTIAL_NOT_FOUND"
MANAGEMENT_ENTITY_NOT_FOUND = "MANAGEMENT_ENTITY_NOT_FOUND"
CREDENTIAL_NAME_CONFLICT = "CREDENTIAL_NAME_CONFLICT"
INVALID_SYSTEM_VISIBILITY = "INVALID_SYSTEM_VISIBILITY"
SYSTEM_CREDENTIAL_ADMIN_REQUIRED = "SYSTEM_CREDENTIAL_ADMIN_REQUIRED"
GATEWAY_DOMAIN_ERROR = "GATEWAY_DOMAIN_ERROR"
GATEWAY_MODEL_NOT_FOUND = "GATEWAY_MODEL_NOT_FOUND"

__all__ = [
    "API_KEY_GATEWAY_GRANT_DENIED",
    "API_KEY_GATEWAY_GRANT_REQUIRED",
    "AUTHENTICATION_ERROR",
    "CHECKPOINT_ERROR",
    "CONFLICT",
    "CREDENTIAL_API_KEY_DECRYPT_ERROR",
    "CREDENTIAL_NAME_CONFLICT",
    "CREDENTIAL_NOT_FOUND",
    "EXTERNAL_SERVICE_ERROR",
    "GATEWAY_DOMAIN_ERROR",
    "GATEWAY_ENTITLEMENT_EXHAUSTED",
    "GATEWAY_MODEL_NOT_FOUND",
    "GATEWAY_TEAM_HEADER_INVALID",
    "GATEWAY_TEAM_HEADER_REQUIRED",
    "GATEWAY_VKEY_TEAM_HEADER_MISMATCH",
    "INTERNAL_ERROR",
    "INVALID_SYSTEM_VISIBILITY",
    "MANAGEMENT_ENTITY_NOT_FOUND",
    "NOT_FOUND",
    "NO_PERSONAL_TEAM_FOR_PROXY",
    "PERMISSION_DENIED",
    "PERSONAL_TEAM_NOT_INITIALIZED",
    "PLATFORM_API_KEY_INVALID",
    "PLATFORM_API_KEY_MISSING_GATEWAY_PROXY_SCOPE",
    "RATE_LIMIT",
    "SYSTEM_CREDENTIAL_ADMIN_REQUIRED",
    "SYSTEM_VIRTUAL_KEY_FORBIDDEN",
    "TEAM_NOT_FOUND",
    "TEAM_PERMISSION_DENIED",
    "TOKEN_ERROR",
    "TOOL_EXECUTION_ERROR",
    "VALIDATION_ERROR",
    "VIRTUAL_KEY_DECRYPT_ERROR",
    "VIRTUAL_KEY_INVALID",
    "VIRTUAL_KEY_NOT_FOUND",
]
