"""Product Info Domain - 产品信息原子能力与常量"""

from domains.agent.domain.product_info.constants import (
    CAPABILITY_COMPETITOR_LINK_ANALYSIS,
    CAPABILITY_DEPENDENCIES,
    CAPABILITY_IDS,
    CAPABILITY_IMAGE_ANALYSIS,
    CAPABILITY_IMAGE_GEN_PROMPTS,
    CAPABILITY_ORDER,
    CAPABILITY_PRODUCT_LINK_ANALYSIS,
    CAPABILITY_VIDEO_SCRIPT,
    DEFAULT_IMAGE_GEN_PROMPTS_8,
    DEFAULT_PROMPTS,
)

__all__ = [
    "CAPABILITY_COMPETITOR_LINK_ANALYSIS",
    "CAPABILITY_DEPENDENCIES",
    "CAPABILITY_IDS",
    "CAPABILITY_IMAGE_ANALYSIS",
    "CAPABILITY_IMAGE_GEN_PROMPTS",
    "CAPABILITY_ORDER",
    "CAPABILITY_PRODUCT_LINK_ANALYSIS",
    "CAPABILITY_VIDEO_SCRIPT",
    "DEFAULT_IMAGE_GEN_PROMPTS_8",
    "DEFAULT_PROMPTS",
]
