-- =============================================================================
-- 生产运维手工执行 | Alembic 运行时不会加载本文件
-- 本地/开发请用: uv run alembic upgrade head  （走 alembic/versions/*.py）
-- versions/20260527_193526_merge_gateway_preflight_and_log_heads.py
-- revision: f31bf0379153
-- down_revision: 20260528_bfrlu, 20260607_gw_pref_idx, 20260607_tenant_route
-- 方向: DOWNGRADE (down.sql)
--   up.sql   = 升级（从 down_revision 升到 revision）
--   down.sql = 回滚（从 revision 退回到 down_revision）
-- 执行后请手工维护 alembic_version.version_num
-- =============================================================================

-- 合并修订（merge revision）：无 DDL / 数据变更（no-op）
